### ISSUE TITLE
Error in `python': double free or corruption on a single Image when using PyTessBaseAPI

### ISSUE THREAD

**Issue by vatsal28** [sirfz/tesserocr#102]
I'm running a docker image of Ubuntu 14.04 and when I'm running the following code:

```
from tesserocr import PyTessBaseAPI
from PIL import Image

x = Image.open('image.jpg')

with PyTessBaseAPI() as api:
    api.SetImage(x)
    api.Recognize()
    ri=api.GetIterator()
    print api.GetUTF8Text()
    
```
I'm getting the following error:

`Segmentation fault (core dumped)`

I did `free -m` and this is what I got:

```
             total       used       free     shared    buffers     cached
Mem:         12012      10280       1731          1        420       8738
-/+ buffers/cache:       1121      10890
Swap:        12284         64      12220

```

Is this a memory issue? 
Does anyone know how to resolve this?

**Comment by simonflueckiger** [comment]
I am currently looking into this. @sirfz you can assign me to this issue if you want.

**Comment by sirfz** [comment]
I don't have the option to assign you @simonflueckiger unfortunately but please consider yourself assigned and thanks for your help!

I think I've seen this issue before, is the result of `api.GetIterator()` null? If so, you can just check if `ri is None` before calling `GetUTF8Text()` to avoid the crash.

**Comment by simonflueckiger** [comment]
This error was most likely due to a faulty build of tesseract. The docker container @vatsal28 was working on had a plethora of tesseract and leptonica include locations (all containing different versions) to choose from. After building again with a clean docker image as our starting point, everything worked just as expected. @sirfz this issue can be closed
