### ISSUE TITLE
Release new version to pypi?

### ISSUE THREAD

**Issue by kba** [sirfz/tesserocr#110]
@sirfz Can you release a new version 2.2.3 or 2.3 to pypi with the version parsing fixes by @bpotard in #98? This would fix #107 #95

**Comment by Caligatio** [comment]
Just to chime in, tesserocr won't build on Ubuntu 18.04 using 2.2.2 but will using the latest here because of #86

**Comment by nijel** [comment]
tesseract 3.05.02 does require c++11, the failed build can be seen here:

https://travis-ci.org/WeblateOrg/weblate/jobs/394918380#L639

It is because of usage of cstdint include introduced in https://github.com/tesseract-ocr/tesseract/commit/d8bd95aca0f4c2a564f7a0ef424d49ffb04cca6f which was added because of https://github.com/tesseract-ocr/tesseract/issues/999 and is part of 3.05.02, 3.05.01 does not contain this.

So having release which does build against 3.05.02 would be great...

**Comment by nijel** [comment]
I've created patch to fix build with 3.05.02 : https://github.com/sirfz/tesserocr/pull/120

**Comment by sirfz** [comment]
Thanks @nijel . PR merged.
