### ISSUE TITLE
OCR of binarized image does not lead to same result as OCR of input image

### ISSUE THREAD

**Issue by lloiodice** [sirfz/tesserocr#132]
I am trying to use Tesseract (latest 4.0 build with fastdata trained data. I can repro this with any page-segmentation option 1,6,12, etc) with B&W images, but I get lower accuracy than when using images produced in color or gray. The quality of my B&W images is equivalent to the binarized images used
by tesseract.

What puzzles me is that when I OCR the binarized image (which is also of course B&W) produced by tesseract I also get lower accuracy.
I was expecting that OCR-ing the binarized image would return the same results as OCR-ing the original input image.

This happens on multiple files (30% of files in my test set ... which are standard emails in normal fonts and B&W) and for example when OCR-ing image.input.tif I get word 'PriceWaterhousCoppers' with confidence 90.
If I send it in B&W including when I use the binarized image produced by Tesseract in the previous step, I get 2 words 'Price' and 'WaterhouseCoopers' with low confidence.

Also posted at:
https://groups.google.com/forum/#!topic/tesseract-ocr/1yf7OE0_7Kk
where I have included the sample images

**Comment by Belval** [comment]
From the top of my head, usually binarizing produces substandard OCR because it implies thresholding the image to decide whether the text is black OR white. This causes the font to lose its quality.

From the images you posted:

Before
![screenshot from 2018-07-14 13-06-26](https://user-images.githubusercontent.com/5399488/42726750-827cceae-8767-11e8-9a95-acec84d73dfd.png)

After
![screenshot from 2018-07-14 13-08-08](https://user-images.githubusercontent.com/5399488/42726752-8bcb4bca-8767-11e8-80fe-d91ba40ab96e.png)

As you can see, the thickness of the letter is reduced considerably which in turns reduces the OCR quality.

Also, while it isn't visible in the images as they aren't true B&W, the gradient between the letter's border and it's center is used in the prediction and binarizing removes it.

**Comment by lloiodice** [comment]
My understanding is that tesseract binarizes the input image and uses this internally binarized image
to recognize text.

You can ask Tesseract to return the binarized image via an API and that is what I did to obtain the image I posted.

I was expecting OCR of any input image and its associated tesseract-binarized image to return the same results.

Unless there is something I do not understand, there could be some issue where given a B&W image, Tesseract somehow reduces its quality before OCR-ing it which would be bad because one of the 
suggestion to improve quality is to give Tesseract B&W images
https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality#binarisation

**Comment by DeliciousHair** [comment]
What @Belval said, with the extra note that I generally find preprocessing via applying a quick sharpening process to the image (edge detection via Laplacian filter then subtract from original image data with appropriate numerical scaling) tends to yield consistently good results with tesseract 4.

Of course, this adds nothing when dealing with CCITT (fax) images since those are already in monochrome, which are always a pain. Preprocessing via binarizing your image is essentially turning decent greyscale image into a crummy CCITT image.

**Comment by amitdo** [comment]
The answers above are excellent.  

The OP asked the same question here:
https://github.com/tesseract-ocr/tesseract/issues/1780

**Comment by M-Fabian** [comment]
I do not find a satisfiying answer to the OP's question. Let me put it differently:

Calling Tesseract with the original image does the following:
1. image -> Tesseract preprocessing and binarization -> intermediate image -> Tesseract recognition -> text result 1

The OP does the following:
1. image -> Tesseract preprocessing and binarization -> intermediate image -> dump to image file (processPages() with tessedit_write_images enabled)
2. dumped image file -> Tesseract recognition -> text result 2

Text result 1 and 2 should be the same because the algorithm is the same, only with a stored intermediate result. According to OP the results differ. I too do not understand why. It seems that the step I call "Tesseract preprocessing and binarization" is not the identity operation if applied to the intermediate image, but then why is that?

I wonder what happens if the intermediate image is passed to Tesseract as a binarized image (as explained here: https://groups.google.com/forum/#!topic/tesseract-ocr/xpxUE7qIWsk). This should bypass "Tesseract preprocessing and binarization" completely, right?

**Comment by M-Fabian** [comment]
This answer was very helpful, thank you :-)
