### ISSUE TITLE
can't  import tesserocr

### ISSUE THREAD

**Issue by yuwan1994** [sirfz/tesserocr#160]
already installed tesserocr ，but can not find the tesserocr
<img width="763" alt="2018-11-18 1 30 15" src="https://user-images.githubusercontent.com/43489344/48702487-01571300-ec2c-11e8-8d89-bed6c742459a.png">
<img width="531" alt="2018-11-18 1 30 55" src="https://user-images.githubusercontent.com/43489344/48702527-1a5fc400-ec2c-11e8-8298-a13fe76b967c.png">

system：Mac OS 10.12.6
Python：3.6.6
tesseract：4.0.0
tesserocr：2.3.1

**Comment by xiejun946** [comment]
please show import error

**Comment by yuwan1994** [comment]
> please show import error

if import tesserocr , then run the program, show:!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 209

**Comment by abhishek-27** [comment]
Pycharm latest version seemed to have the issue where even after installing it wasn't able to import tesserocr. So I downgraded my Pycharm to the version 2018.1.6 and the import error for tesserocr got fixed.

If locale error then it can be fixed by either importing export LC_ALL=C in terminal or setting it in the python file where you are using tesserocr as locale.setlocale(locale.LC_ALL, 'C') or if still getting error in Pycharm IDE then just set LC_ALL=C as Environment variable in the run configuration for that file.

**Comment by kimgysen** [comment]
I have the same problem using the official installation instructions. Being trying to fix the error: 

`ModuleNotFoundError: No module named 'tesserocr' `

For hours. 
Issue is open since december last year. 
If this can't be resolved, then this is library is pretty much useless... 
Not going to spend hours in other people's mess.

**Comment by neuneck** [comment]
I can corroborate that on python3.7.5, with tesserocr version 2.5.0 a segfault appears on import if the locale has not been set to "C".

**Comment by sirfz** [comment]
The locale issue has been addressed already and was related to tesseract itself and not tesserocr. It's already been fixed in tesseract 4.1 (see #165)
