### ISSUE TITLE
how to install tesserocr on windows

### ISSUE THREAD

**Issue by umutozgur** [sirfz/tesserocr#266]
I'm trying to install with conda but it keeps giving the following error

![image](https://user-images.githubusercontent.com/3484899/128991726-aa15a022-363f-4b83-9cd2-b30494380a31.png)

**Comment by parulsingh23** [comment]
@umutozgur I have been having the same issue. I have tried all 3 methods to install (on Windows 10), and none worked. I am getting the exact same `failed with initial frozen solve` when I run conda-forge. 
I realized I can't run the pip install because I have python 3.9. And when carrying out the section for [zlib build and installation](https://github.com/sirfz/tesserocr/blob/master/Windows.build.md#zlib-build-and-installation), I am getting an error when I run `"C:\Program Files\CMake\bin\cmake.exe"  --build . --config Release --target install`:
```
CMake Error at cmake_install.cmake:55 (file):
    file cannot create directory: C:/zlib-1.2.11/build.msvs/:/win64/lib.  Maybe
    need administrative privileges.


C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: The command "setlocal [C:\zlib-1.2.11\build.msvs\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Micro
soft\CMake\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake [C:\zlib-1.2.11\build.msvs\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [C:\zlib-1.2.11\build.msvs\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: :cmEnd [C:\zlib-1.2.11\build.msvs\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\zlib-1.2.11\build.msvs\install.vcxpr
oj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: :cmErrorLevel [C:\zlib-1.2.11\build.msvs\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: exit /b %1 [C:\zlib-1.2.11\build.msvs\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: :cmDone [C:\zlib-1.2.11\build.msvs\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [C:\zlib-1.2.11\build.msvs\install.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(15
5,5): error MSB3073: :VCEnd" exited with code 1. [C:\zlib-1.2.11\build.msvs\install.vcxproj]
```

**Comment by zdenop** [comment]
>     file cannot create directory: C:/zlib-1.2.11/build.msvs/:/win64/lib.  

This indicates that you made error during cmake configuration - ":" is not accepted character for windows path...

**Comment by parulsingh23** [comment]
@zdenop thanks so much for the response! So since the error is in the cmake configuration, would that specifically be in this command:
`cmake .. -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR%`?

Since this invovles the `INSTALL_DIR` env variable, I believe this is due to my setting up of the [Destination for dependencies](https://github.com/sirfz/tesserocr/blob/master/Windows.build.md#initialisation-of-project-structure). 
```
mkdir F:\win64
set INSTALL_DIR=F:\win64
set PATH=%PATH%;%INSTALL_DIR%\bin
```
When I run the fist command `mkdir F:\win64`, I get the error: `The system cannot find the drive specified.` And I've never seen a path with `F:\` before. So I simply changed the command to `mkdir win64` (such that the file path is now C:\win64), and had changed the second terminal command to `set INSTALL_DIR=\win64`. 

However, I'm not sure how to proceed, as going back, I tried to set INSTALL_DIR to `win64`, `F:\win64`, and `C:\win64`, but none fixed the error I get later.

**Comment by zdenop** [comment]
IMO `INSTALL_DIR` should be absolute and **existing path**. So if you do not have drive `F`, use other existing. 
Using `C` drive is/could be complicated as it usually is used for system, where you do not want to run out of free space and it should be restricted in term of privileges...

**Comment by umutozgur** [comment]
I solved the problem. I installed anaconda first. then i created one env (`create env test`). then after I activate it (`conda activate test`), I installed the tesseract.
