### ISSUE TITLE
Publish wheels for aarch64

### ISSUE THREAD

**Issue by nijel** [sirfz/tesserocr#322]
Would it be possible to publish wheels for linux aarch64 as well? It is quite widely used platform and cibuildwheel supports that, see https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation

**Comment by sirfz** [comment]
tagging @betaboon for some input as they are the ones who contributed the current Github Actions build workflow

**Comment by betaboon** [comment]
back when i added the github-pipelines i also tried to add aarch64-builds through qemu. that is quite easily possible. but building tesseract in qemu takes quite a long time, that's why i opted to not include that in the PRs.

cibuildwheel documentation on that can be found [here](https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation).
